# Generated by Django 5.2.3 on 2025-08-12 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_image_post_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Personal', 'Personal'), ('Veterinary', 'Veterinary'), ('Literature', 'Literature'), ('Art', 'Art')], default='Personal', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='subcategory',
            field=models.CharField(blank=True, choices=[('personal', 'Personal'), ('Experiences', 'Experiences'), ('case studies', 'Case Studies'), ('projects', 'Projects'), ('Articles', 'Articles'), ('Power point Presentation', 'Power point Presentation'), ('stories', 'Stories'), ('novels', 'Novels'), ('Poems', 'Poems'), ('Autobiography', 'Autobiography'), ('Drawings', 'Drawings'), ('paintings', 'Paintings'), ('Crafts', 'Crafts')], max_length=30, null=True),
        ),
    ]
