# Generated by Django 5.2.3 on 2025-08-22 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_comment_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='subcategory',
            field=models.CharField(blank=True, choices=[('personal', 'Personal'), ('Experiences', 'Experiences'), ('case studies', 'Case Studies'), ('projects', 'Projects'), ('Articles', 'Articles'), ('files', 'Files'), ('stories', 'Stories'), ('novels', 'Novels'), ('Poems', 'Poems'), ('Autobiography', 'Autobiography'), ('Drawings', 'Drawings'), ('paintings', 'Paintings'), ('Crafts', 'Crafts')], max_length=30, null=True),
        ),
    ]
